enable_custom_js:
  type: bool
  default: true
  description: "Enable custom JavaScript functionality"

custom_header_text:
  type: string
  default: ""
  description: "Custom text to display in the header"

primary_brand_color:
  type: string
  default: "#1f8dd6"
  description: "Primary brand color for the theme"

show_welcome_banner:
  type: bool
  default: false
  description: "Show a welcome banner on the homepage"

welcome_banner_header_logged_in:
  type: string
  default: "Welcome back, {username}!"
  description: "Main header text for logged-in users (use {username} as placeholder)"

welcome_banner_header_guest:
  type: string
  default: "Welcome to Our Community"
  description: "Main header text for guests"

welcome_banner_subtitle:
  type: string
  default: "Find help, share your knowledge, and experience fast inference"
  description: "Subtitle text (h2) shown below the main header"

show_banner_search:
  type: bool
  default: true
  description: "Show search bar in the welcome banner"

custom_footer_text:
  type: string
  default: ""
  description: "Custom text to display in the footer"

enable_animations:
  type: bool
  default: true
  description: "Enable CSS animations and transitions"

show_alert_banner:
  type: bool
  default: false
  description: "Show a custom alert banner on the homepage"

alert_banner_message:
  type: string
  default: "Important announcement: Check out our latest updates and features!"
  description: "Message text for the alert banner"

alert_banner_color:
  type: string
  default: "#ff6a39"
  description: "Background color for the alert banner (hex color)"

alert_banner_cta_text:
  type: string
  default: "Learn More"
  description: "Text for the call-to-action button"

alert_banner_cta_url:
  type: string
  default: ""
  description: "URL for the call-to-action button (can be relative like '/about' or external like 'https://example.com')"

show_feature_banner:
  type: bool
  default: true
  description: "Show the 3-column feature banner on homepage"

feature_banner_item_1_title:
  type: string
  default: "Fast & Powerful"
  description: "Title for the first feature banner item"

feature_banner_item_1_image:
  type: string
  default: ""
  description: "Image URL for the first feature banner item (use relative path like 'assets/feature1.png' for local assets or full URL for external images)"

feature_banner_item_1_url:
  type: string
  default: ""
  description: "URL to link to when clicking the first feature banner item (can be relative like '/about' or external like 'https://example.com')"

feature_banner_item_2_title:
  type: string
  default: "Community Driven"
  description: "Title for the second feature banner item"

feature_banner_item_2_image:
  type: string
  default: ""
  description: "Image URL for the second feature banner item (use relative path like 'assets/feature2.png' for local assets or full URL for external images)"

feature_banner_item_2_url:
  type: string
  default: ""
  description: "URL to link to when clicking the second feature banner item (can be relative like '/about' or external like 'https://example.com')"

feature_banner_item_3_title:
  type: string
  default: "Always Learning"
  description: "Title for the third feature banner item"

feature_banner_item_3_image:
  type: string
  default: ""
  description: "Image URL for the third feature banner item (use relative path like 'assets/feature3.png' for local assets or full URL for external images)"

feature_banner_item_3_url:
  type: string
  default: ""
  description: "URL to link to when clicking the third feature banner item (can be relative like '/about' or external like 'https://example.com')" 