enable_custom_js:
  type: bool
  default: true
  description: "Enable custom JavaScript functionality"

custom_header_text:
  type: string
  default: ""
  description: "Custom text to display in the header"

primary_brand_color:
  type: string
  default: "#1f8dd6"
  description: "Primary brand color for the theme"

show_welcome_banner:
  type: bool
  default: false
  description: "Show a welcome banner on the homepage"

welcome_banner_text:
  type: string
  default: "Welcome to our Groqsters community!"
  description: "Text to display in the welcome banner"

custom_footer_text:
  type: string
  default: ""
  description: "Custom text to display in the footer"

enable_animations:
  type: bool
  default: true
  description: "Enable CSS animations and transitions"

show_feature_banner:
  type: bool
  default: true
  description: "Show the 3-column feature banner on homepage"

feature_banner_item_1_title:
  type: string
  default: "Fast & Powerful"
  description: "Title for the first feature banner item"

feature_banner_item_1_image:
  type: string
  default: ""
  description: "Image URL for the first feature banner item (use relative path like 'assets/feature1.png' for local assets or full URL for external images)"

feature_banner_item_2_title:
  type: string
  default: "Community Driven"
  description: "Title for the second feature banner item"

feature_banner_item_2_image:
  type: string
  default: ""
  description: "Image URL for the second feature banner item (use relative path like 'assets/feature2.png' for local assets or full URL for external images)"

feature_banner_item_3_title:
  type: string
  default: "Always Learning"
  description: "Title for the third feature banner item"

feature_banner_item_3_image:
  type: string
  default: ""
  description: "Image URL for the third feature banner item (use relative path like 'assets/feature3.png' for local assets or full URL for external images)"

feature_banner_fallback_icon_1:
  type: string
  default: "⚡"
  description: "Fallback emoji/icon for first item if image fails to load"

feature_banner_fallback_icon_2:
  type: string
  default: "🤝"
  description: "Fallback emoji/icon for second item if image fails to load"

feature_banner_fallback_icon_3:
  type: string
  default: "🚀"
  description: "Fallback emoji/icon for third item if image fails to load" 